Repository broadinstitute/gatk, pull requests merged in 2018-07, with the labels that each got.

#4982 Add optional summary table output to ValidateBasicSomaticShortMutations
  src/main/java/org/broadinstitute/hellbender/tools/walkers/validation/basicshortmutpileup/ValidateBasicSomaticShortMutations.java
  src/test/java/org/broadinstitute/hellbender/tools/walkers/validation/basicshortmutpileup/ValidateBasicSomaticShortMutationsIntegrationTest.java
Labels: Evaluation, Mutect

#4645 GenomicsDBImport: Modifications in order to address GATK issue #3269
  build.gradle
  src/main/java/org/broadinstitute/hellbender/engine/FeatureDataSource.java
  src/main/java/org/broadinstitute/hellbender/tools/genomicsdb/GenomicsDBConstants.java
  src/main/java/org/broadinstitute/hellbender/tools/genomicsdb/GenomicsDBImport.java
  src/test/java/org/broadinstitute/hellbender/engine/GenomicsDBIntegrationTest.java
  src/test/java/org/broadinstitute/hellbender/tools/genomicsdb/GenomicsDBImportIntegrationTest.java
  src/test/java/org/broadinstitute/hellbender/tools/genomicsdb/GenomicsDBImportUnitTest.java
  src/test/resources/large/gvcfs/HG00096_after_combine_gvcfs.g.vcf.gz
  src/test/resources/large/gvcfs/HG00096_after_combine_gvcfs.g.vcf.gz.tbi
  src/test/resources/large/gvcfs/HG00268_after_combine_gvcfs.g.vcf.gz
  src/test/resources/large/gvcfs/HG00268_after_combine_gvcfs.g.vcf.gz.tbi
  src/test/resources/large/gvcfs/NA19625_after_combine_gvcfs.g.vcf.gz
  src/test/resources/large/gvcfs/NA19625_after_combine_gvcfs.g.vcf.gz.tbi
  src/test/resources/large/gvcfs/combined.gatk3.7_sites_only.g.vcf.gz
  src/test/resources/large/gvcfs/combined.gatk3.7_sites_only.g.vcf.gz.tbi
  src/test/resources/large/gvcfs/combined_multi_interval.gatk3.7.g.vcf.gz
  src/test/resources/large/gvcfs/combined_multi_interval.gatk3.7.g.vcf.gz.tbi
  src/test/resources/large/gvcfs/combined_with_genotypes.g.vcf.gz
  src/test/resources/large/gvcfs/combined_with_genotypes.g.vcf.gz.tbi
Labels: GenomicsDB

#4980 fixes new qual regression in 4.0.5.0
  src/main/java/org/broadinstitute/hellbender/tools/walkers/genotyper/afcalc/AlleleFrequencyCalculator.java
  src/test/java/org/broadinstitute/hellbender/tools/walkers/genotyper/afcalc/AlleleFrequencyCalculatorUnitTest.java
Labels: bug

#4956 Fix position annotations to use position in original, not clipped, read
  src/main/java/org/broadinstitute/hellbender/engine/FeatureDataSource.java
  src/main/java/org/broadinstitute/hellbender/tools/walkers/annotator/BaseQuality.java
  src/main/java/org/broadinstitute/hellbender/tools/walkers/annotator/ClippingRankSumTest.java
  src/main/java/org/broadinstitute/hellbender/tools/walkers/annotator/ReadPosRankSumTest.java
  src/main/java/org/broadinstitute/hellbender/tools/walkers/annotator/ReadPosition.java
  src/main/java/org/broadinstitute/hellbender/tools/walkers/haplotypecaller/AssemblyBasedCallerGenotypingEngine.java
  src/main/java/org/broadinstitute/hellbender/utils/genotyper/ReadLikelihoods.java
  src/main/java/org/broadinstitute/hellbender/utils/genotyper/UnfilledReadsLikelihoods.java
  src/main/java/org/broadinstitute/hellbender/utils/read/AlignmentUtils.java
  src/test/java/org/broadinstitute/hellbender/cmdline/GATKPlugin/GATKAnnotationPluginDescriptorUnitTest.java
  src/test/java/org/broadinstitute/hellbender/utils/genotyper/ReadLikelihoodsUnitTest.java
  src/test/resources/org/broadinstitute/hellbender/tools/haplotypecaller/expected.testGVCFMode.gatk4.alleleSpecific.g.vcf
  src/test/resources/org/broadinstitute/hellbender/tools/haplotypecaller/expected.testGVCFMode.gatk4.g.vcf
  src/test/resources/org/broadinstitute/hellbender/tools/haplotypecaller/expected.testGVCFMode.gatk4.g.vcf.idx
  src/test/resources/org/broadinstitute/hellbender/tools/haplotypecaller/expected.testGenotypeGivenAllelesMode.gatk4.vcf
  src/test/resources/org/broadinstitute/hellbender/tools/haplotypecaller/expected.testHaplotypeCallerRemoveAltAlleleBasedOnHaptypeScores.gatk4.vcf
  src/test/resources/org/broadinstitute/hellbender/tools/haplotypecaller/expected.testVCFMode.gatk4.vcf
Labels: Annotations

#4970 (SV) slim down REF column for CPX variants
  src/main/java/org/broadinstitute/hellbender/tools/spark/sv/discovery/inference/CpxVariantInterpreter.java
  src/main/java/org/broadinstitute/hellbender/tools/spark/sv/discovery/inference/SegmentedCpxVariantSimpleVariantExtractor.java
  src/test/java/org/broadinstitute/hellbender/tools/spark/sv/discovery/inference/CpxVariantInterpreterUnitTest.java
  src/test/java/org/broadinstitute/hellbender/tools/spark/sv/discovery/inference/SegmentedCpxVariantSimpleVariantExtractorUnitTest.java
  src/test/resources/org/broadinstitute/hellbender/tools/spark/sv/integration/inputs/CpxVariantReInterpreterSparkIntegrationTest_complex.vcf
Labels: SV, enhancement

#5008 docs for new qual model
  docs/gatk_qual.pdf
  docs/gatk_qual.tex
Labels: HaplotypeCaller, UserDoc

#4941 Making MAF become the output of Funcotator in M2 WDL and multiple transcript fix.
  scripts/m2_cromwell_tests/run_m2_wdl.sh
  scripts/m2_cromwell_tests/test_m2_wdl_multi.json
  scripts/mutect2_wdl/mutect2.wdl
  scripts/mutect2_wdl/mutect2_multi_sample.wdl
  scripts/mutect2_wdl/mutect2_nio.wdl
  src/main/java/org/broadinstitute/hellbender/tools/funcotator/dataSources/gencode/GencodeFuncotationFactory.java
  src/main/java/org/broadinstitute/hellbender/tools/funcotator/mafOutput/CustomMafFuncotationCreator.java
  src/main/java/org/broadinstitute/hellbender/tools/funcotator/mafOutput/MafOutputRenderer.java
  src/test/java/org/broadinstitute/hellbender/tools/funcotator/FuncotatorIntegrationTest.java
  src/test/java/org/broadinstitute/hellbender/tools/funcotator/dataSources/gencode/GencodeFuncotationFactoryUnitTest.java
  src/test/resources/org/broadinstitute/hellbender/tools/funcotator/gencode.v19.CNTN4.annotation.gtf
  src/test/resources/org/broadinstitute/hellbender/tools/funcotator/gencode.v19.CNTN4.pc_transcripts.dict
  src/test/resources/org/broadinstitute/hellbender/tools/funcotator/gencode.v19.CNTN4.pc_transcripts.fasta
  src/test/resources/org/broadinstitute/hellbender/tools/funcotator/gencode.v19.CNTN4.pc_transcripts.fasta.fai
Labels: Funcotator, PRIORITY_HIGH

#5031 extracted method for streaming a vcf
  src/main/java/org/broadinstitute/hellbender/utils/Utils.java
  src/main/java/org/broadinstitute/hellbender/utils/test/VariantContextTestUtils.java
  src/test/java/org/broadinstitute/hellbender/tools/walkers/haplotypecaller/HaplotypeCallerIntegrationTest.java
  src/test/java/org/broadinstitute/hellbender/tools/walkers/mutect/CreateSomaticPanelOfNormalsIntegrationTest.java
  src/test/java/org/broadinstitute/hellbender/tools/walkers/mutect/Mutect2IntegrationTest.java
  src/test/java/org/broadinstitute/hellbender/tools/walkers/validation/AnnotateVcfWithBamDepthIntegrationTest.java
  src/test/java/org/broadinstitute/hellbender/tools/walkers/validation/AnnotateVcfWithExpectedAlleleFractionIntegrationTest.java
  src/test/java/org/broadinstitute/hellbender/tools/walkers/validation/ConcordanceIntegrationTest.java
  src/test/java/org/broadinstitute/hellbender/tools/walkers/validation/RemoveNearbyIndelsIntegrationTest.java
Labels: coding

#4977 VCF Funcotation Factory will recognize equivalent alleles (even when not exact)
  src/main/java/org/broadinstitute/hellbender/tools/funcotator/dataSources/TableFuncotation.java
  src/main/java/org/broadinstitute/hellbender/tools/funcotator/dataSources/vcf/VcfFuncotationFactory.java
  src/main/java/org/broadinstitute/hellbender/utils/variant/GATKVariantContextUtils.java
  src/test/java/org/broadinstitute/hellbender/tools/funcotator/dataSources/vcf/VcfFuncotationFactoryUnitTest.java
  src/test/java/org/broadinstitute/hellbender/utils/variant/GATKVariantContextUtilsUnitTest.java
  src/test/resources/org/broadinstitute/hellbender/tools/funcotator/test_exac.vcf
  src/test/resources/org/broadinstitute/hellbender/tools/funcotator/test_exac.vcf.idx
Labels: Funcotator, FuncotatorBetaBlocker

#4971 (SV) clean up and add documentation to AssemblyContigAlignmentsConfigPicker
  src/main/java/org/broadinstitute/hellbender/tools/spark/sv/discovery/alignment/AssemblyContigAlignmentsConfigPicker.java
  src/test/java/org/broadinstitute/hellbender/tools/spark/sv/discovery/TestUtilsForAssemblyBasedSVDiscovery.java
  src/test/java/org/broadinstitute/hellbender/tools/spark/sv/discovery/alignment/AssemblyContigAlignmentsConfigPickerUnitTest.java
  src/test/java/org/broadinstitute/hellbender/tools/spark/sv/discovery/inference/TestUtilsCpxVariantInference.java
Labels: SV, enhancement

#5030 Camel-cased some methods in ClippingOp
  src/main/java/org/broadinstitute/hellbender/engine/filters/OverclippedReadFilter.java
  src/main/java/org/broadinstitute/hellbender/tools/walkers/rnaseq/OverhangFixingManager.java
  src/main/java/org/broadinstitute/hellbender/utils/bwa/BwaMemAlignmentUtils.java
  src/main/java/org/broadinstitute/hellbender/utils/clipping/ClippingOp.java
  src/main/java/org/broadinstitute/hellbender/utils/clipping/ReadClipper.java
  src/main/java/org/broadinstitute/hellbender/utils/smithwaterman/SmithWatermanJavaAligner.java
  src/test/java/org/broadinstitute/hellbender/engine/filters/OverclippedReadFilterUnitTest.java
  src/test/java/org/broadinstitute/hellbender/tools/spark/sv/utils/SVFastqUtilsUnitTest.java
  src/test/java/org/broadinstitute/hellbender/utils/clipping/ReadClipperUnitTest.java
  src/test/java/org/broadinstitute/hellbender/utils/read/CigarUtilsUnitTest.java
  src/test/java/org/broadinstitute/hellbender/utils/read/markduplicates/ReadsKeyUnitTest.java
  src/test/java/org/broadinstitute/hellbender/utils/smithwaterman/SmithWatermanAlignerAbstractUnitTest.java
Labels: coding, learn GATK

#5038 Fix an edge case bug in PalindromeArtifactReadTransformer
  src/main/java/org/broadinstitute/hellbender/tools/walkers/mutect/Mutect2.java
  src/main/java/org/broadinstitute/hellbender/transformers/PalindromeArtifactClipReadTransformer.java
Labels: Mutect, bug

#5044 (SV) more alignment edge cases
  src/main/java/org/broadinstitute/hellbender/tools/spark/sv/discovery/alignment/AssemblyContigAlignmentsConfigPicker.java
  src/main/java/org/broadinstitute/hellbender/tools/spark/sv/discovery/inference/ContigChimericAlignmentIterativeInterpreter.java
  src/main/java/org/broadinstitute/hellbender/tools/spark/sv/utils/SVInterval.java
  src/test/java/org/broadinstitute/hellbender/tools/spark/sv/discovery/alignment/AssemblyContigAlignmentsConfigPickerUnitTest.java
  src/test/java/org/broadinstitute/hellbender/tools/spark/sv/utils/SVIntervalUnitTest.java
Labels: PRIORITY_HIGH, SV

#4769 Add BreakpointEvidence filter based on classifier
  build.gradle
  scripts/sv/create_cluster.sh
  scripts/sv/manage_sv_pipeline.sh
  scripts/sv/run_whole_pipeline.sh
  scripts/sv/sanity_checks.sh
  src/main/java/org/broadinstitute/hellbender/tools/spark/sv/StructuralVariationDiscoveryArgumentCollection.java
  src/main/java/org/broadinstitute/hellbender/tools/spark/sv/evidence/BreakpointDensityFilter.java
  src/main/java/org/broadinstitute/hellbender/tools/spark/sv/evidence/BreakpointEvidence.java
  src/main/java/org/broadinstitute/hellbender/tools/spark/sv/evidence/EvidenceFeatures.java
  src/main/java/org/broadinstitute/hellbender/tools/spark/sv/evidence/EvidenceOverlapChecker.java
  src/main/java/org/broadinstitute/hellbender/tools/spark/sv/evidence/FindBreakpointEvidenceSpark.java
  src/main/java/org/broadinstitute/hellbender/tools/spark/sv/evidence/ReadMetadata.java
  src/main/java/org/broadinstitute/hellbender/tools/spark/sv/evidence/XGBoostEvidenceFilter.java
  src/main/java/org/broadinstitute/hellbender/tools/spark/sv/utils/SVInterval.java
  src/main/java/org/broadinstitute/hellbender/tools/spark/utils/IntHistogram.java
  src/main/resources/large/sv_evidence_classifier.bin
  src/test/java/org/broadinstitute/hellbender/tools/spark/sv/evidence/BreakpointDensityFilterTest.java
  src/test/java/org/broadinstitute/hellbender/tools/spark/sv/evidence/FindBreakpointEvidenceSparkUnitTest.java
  src/test/java/org/broadinstitute/hellbender/tools/spark/sv/evidence/XGBoostEvidenceFilterUnitTest.java
  src/test/java/org/broadinstitute/hellbender/tools/spark/sv/integration/FindBreakpointEvidenceSparkIntegrationTest.java
  src/test/java/org/broadinstitute/hellbender/tools/spark/sv/integration/SVIntegrationTestDataProvider.java
  src/test/resources/large/SVIntegrationTest_hg19_gaps.bed.gz
  src/test/resources/large/SVIntegrationTest_hg19_gaps.bed.gz.tbi
  src/test/resources/large/SVIntegrationTest_hg19_umap_s100.bed.gz
  src/test/resources/large/SVIntegrationTest_hg19_umap_s100.bed.gz.tbi
  src/test/resources/large/SVIntegrationTest_hg19_umap_s50.bed.gz
  src/test/resources/large/SVIntegrationTest_hg19_umap_s50.bed.gz.tbi
  src/test/resources/org/broadinstitute/hellbender/tools/spark/sv/evidence/FindBreakpointEvidenceSpark/hg38_gaps.bed.gz
  src/test/resources/org/broadinstitute/hellbender/tools/spark/sv/evidence/FindBreakpointEvidenceSpark/hg38_gaps.bed.gz.tbi
  src/test/resources/org/broadinstitute/hellbender/tools/spark/sv/evidence/FindBreakpointEvidenceSpark/hg38_umap_s100.bed.gz
  src/test/resources/org/broadinstitute/hellbender/tools/spark/sv/evidence/FindBreakpointEvidenceSpark/hg38_umap_s100.bed.gz.tbi
  src/test/resources/org/broadinstitute/hellbender/tools/spark/sv/evidence/FindBreakpointEvidenceSpark/sv_classifier_test_data.json
  src/test/resources/org/broadinstitute/hellbender/tools/spark/sv/evidence/FindBreakpointEvidenceSpark/sv_features_test_data.json
  src/test/resources/org/broadinstitute/hellbender/tools/spark/sv/integration/inputs/hg19_DEL_contigAssemblies_XGBOOST.sam
Labels: SV

#5049 Added maxRetries to runtime in M2 WDLs
  scripts/mutect2_wdl/mutect2.wdl
  scripts/mutect2_wdl/mutect2_nio.wdl
  scripts/mutect2_wdl/mutect2_pon.wdl
Labels: wdl

#5057 M2 doesn't use very short stubs of clipped reads for genotyping
  src/main/java/org/broadinstitute/hellbender/tools/walkers/mutect/Mutect2Engine.java
  src/test/java/org/broadinstitute/hellbender/tools/walkers/mutect/Mutect2IntegrationTest.java
  src/test/resources/org/broadinstitute/hellbender/tools/mutect/mito/Homo_sapiens_assembly38.mt_only.dict
  src/test/resources/org/broadinstitute/hellbender/tools/mutect/mito/Homo_sapiens_assembly38.mt_only.fasta
  src/test/resources/org/broadinstitute/hellbender/tools/mutect/mito/Homo_sapiens_assembly38.mt_only.fasta.fai
  src/test/resources/org/broadinstitute/hellbender/tools/mutect/mito/NA12878.bai
  src/test/resources/org/broadinstitute/hellbender/tools/mutect/mito/NA12878.bam
Labels: Mutect, bug
