Repository broadinstitute/gatk, pull requests merged in 2023-06, with the labels that each got.

#8361 Innocuous housekeeping changes in the partially determined haplotypes code
  src/main/java/org/broadinstitute/hellbender/tools/walkers/haplotypecaller/AlleleLikelihoodWriter.java
  src/main/java/org/broadinstitute/hellbender/tools/walkers/haplotypecaller/HaplotypeCallerEngine.java
  src/main/java/org/broadinstitute/hellbender/tools/walkers/haplotypecaller/PartiallyDeterminedHaplotypeComputationEngine.java
  src/main/java/org/broadinstitute/hellbender/tools/walkers/haplotypecaller/ramps/RampUtils.java
  src/main/java/org/broadinstitute/hellbender/tools/walkers/haplotypecaller/readthreading/ReadThreadingAssembler.java
  src/main/java/org/broadinstitute/hellbender/utils/Utils.java
  src/main/java/org/broadinstitute/hellbender/utils/haplotype/EventMap.java
  src/main/java/org/broadinstitute/hellbender/utils/haplotype/Haplotype.java
  src/main/java/org/broadinstitute/hellbender/utils/haplotype/PartiallyDeterminedHaplotype.java
  src/test/java/org/broadinstitute/hellbender/tools/walkers/haplotypecaller/PartiallyDeterminedHaplotypeComputationEngineUnitTest.java
  src/test/java/org/broadinstitute/hellbender/utils/haplotype/HaplotypeUnitTest.java
Labels: refactoring, DRAGEN-GATK

#8366 graph method for PDHMM event groups that unifies finding/merging and overlap/mutual exclusion
  src/main/java/org/broadinstitute/hellbender/tools/walkers/haplotypecaller/PartiallyDeterminedHaplotypeComputationEngine.java
Labels: DRAGEN-GATK

#8391 Pinning joblib for compatibility with python version
  scripts/gatkcondaenv.yml.template
Labels: Python
